services:
  postgres:
    image: postgres:16
    ports:
      - "5434:5432"
    environment:
      POSTGRES_USER: coti_user
      POSTGRES_PASSWORD: coti_password
      POSTGRES_DB: bd_produtosApi
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
